# Generated by Django 5.1.7 on 2025-03-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='month',
            field=models.DateField(),
        ),
    ]
